spring.application.name=demo
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.url=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui/index.html
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
